### PR TITLE
Load all keys from ssh agent if no specific `AuthMethods` is passed

### PR DESCRIPTION
**Pull request by jadolg**
This should solve the problem I mention in #161

### CODE REVIEW

**Comment by jadolg** [comment]
The failed tests are failing for `main` too at least for me :thinking: 

image

**Comment by kke** [comment]
They were passing in the previous PR 🤔

**Comment by kke** [comment]
https://github.com/k0sproject/rig/pull/163 tests seem to pass.

**Comment by jadolg** [comment]
> #163

I found where the problem was in my machine. I was missing one dependency.
I have fixed the problem that broke the test and wrote a test to reproduce my issue.
Unfortunately, my solution does not fix the issue. :disappointed: 
I'll continue debugging.
The test suit is not the easiest thing to run, unfortunately.

**Comment by kke** [comment]
The linting errors are from `main`.

**Comment by jadolg** [comment]
> The linting errors are from `main`.

So it worked :rocket: :partying_face:

**Pull request merged**
