### PR TITLE
fixed sudo, mode and newline in LineIntoFile

### PR DESCRIPTION
**Pull request by CaptainQwark**
new pull req that fixes all issues with LineIntoFile. (see also #56)

I realise that I probably should just have fixed the #56 one and not start over again. sorry for that.

Alex

### CODE REVIEW

**Comment by kke** [comment]
I'd rather see the it accept exec options than always using sudo:

```
func (c Linux) LineIntoFile(h Host, path, matcher, newLine string, opts ...exec.Option) error {
   return h.Exec(whatever, opts...)
}
```

Even better would be to reimplement it completely in Go (read file, modify in memory, write back) as the `TODO` says: 

```
// TODO refactor this into go because it's too magical.
```

**Comment by CaptainQwark** [comment]
I don't really see the problem. If this would be done entirely in go (which would indeed be better), it would effectively run as 'sudo' as well, since the new file that is created if one did not exist before, is also owned by root.

I'm not a go programmer so I can't make your clean solution, I'm just trying to help and fix something that is currently broken.

**Comment by kke** [comment]
> I don't really see the problem. If this would be done entirely in go (which would indeed be better), it would effectively run as 'sudo' as well, since the new file that is created if one did not exist before, is also owned by root.

That's where the exec options come to play, this also applies to the shell version.

**Comment by kke** [comment]
Doing that will require altering WriteFile or writing the new file in the shell snippet.

**Comment by kke** [comment]
I just noticed there's no windows LineIntoFile at all, that's a bit bad for compatibility :( I'll look into it.

**Pull request closed without merging**
